# Site settings
title: Taylor Trimble
email: taylor@taylortrimble.com
username: tylrtrmbl
description: "Taylor's minimum viable blog."
baseurl: ""
url: "http://taylortrimble.com"
timezone: "America/Los_Angeles"

# Build settings
markdown: kramdown
permalink: pretty
